objectTypeMappings:
  Adres:
    sourceRoot: bag:Nummeraanduiding
    propertyMappings:
      identificatie:
        pathMapping:
          path: identificatie
      huisnummer:
        pathMapping:
          path: huisnummer
      huisnummertoevoeging:
        pathMapping:
          path: huisnummertoevoeging
      huisletter:
        pathMapping:
          path: huisletter
      postcode:
        pathMapping:
          path: postcode
      straatnaam:
        pathMapping:
          path: ligtAan/naam
      plaatsnaam:
        pathMappings:
          - ligtIn/naam
          - path: ligtAan/ligtIn/naam
            combiner: coalesce
      isHoofdadres:
        pathMapping:
          path: isHoofdadresVan/identificatie
          transform: nonNull
      omschrijving:
        pathMappings:
          - ligtAan/naam
          - path: huisnummer
            combiner:
              name: concat
              prefix: ' '
          - path: huisletter
            combiner:
              name: concat
              prefix: ' '
          - path: huisnummertoevoeging
            combiner:
              name: concat
              prefix: '-'
