objectTypeMappings:
  Address:
    sourceRoot: bag:Nummeraanduiding
    propertyMappings:
      addressID:
        pathMappings:
          path: identificatie
      locatorDesignator:
        pathMappings:
          - path: huisnummer
            map:
              type: toString
          - path: huisnummertoevoeging
            map:
              type: prepend
              options:
                prefix: ' '
          - path: huisletter
            map:
              type: prepend
              options:
                prefix: ' '
      postCode:
        pathMappings:
          path: postcode
      postName:
        pathMappings:
          path: ligtIn/naam
          next:
            path: ligtAan/ligtIn/naam
            ifMatch:
              type: isNull
      thoroughfare:
        pathMappings:
          path: ligtAan/naam
      fullAddress:
        pathMappings:
          - path: ligtAan/naam
          - path: huisnummer
            map:
              type: prepend
              options:
                prefix: ' '
          - path: huisletter
            map:
              type: prepend
              options:
                prefix: ' '
          - path: huisnummertoevoeging
            map:
              type: prepend
              options:
                prefix: '-'
          - path: postcode
            map:
              type: prepend
              options:
                prefix: ' '
          - path: ligtIn/naam
            next:
              path: ligtAan/ligtIn/naam
              ifMatch:
                type: isNull
            map:
              type: prepend
              options:
                prefix: ' '
