logging:
  level:
    root: INFO
    nl.geostandaarden.imx.orchestrate: DEBUG

orchestrate:
  mapping: ../data/geo/mapping.yaml
  sources:
    adr:
      type: file
      options:
        dataPath: ../data/adr
    city:
      type: file
      options:
        dataPath: ../data/city
    land:
      type: file
      options:
        dataPath: ../data/land
